# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallDetectHandler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for CallDetectHandler

end

target 'Clientell' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!

      modules_path = '../node_modules'
      rn_path = "#{modules_path}/react-native"
      rn_maps_path = "#{modules_path}/react-native-maps"

      # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
      pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
      pod 'React', path: rn_path, subspecs: [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
      ]

      # Firebase Related pods
      pod 'Firebase/Analytics'

      # React Native third party dependencies podspecs
      pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
      pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
      pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

      post_install do |installer|
          installer.pods_project.targets.each do |target|

            # The following is needed to ensure the "archive" step works in XCode.
            # It removes React & Yoga from the Pods project, as it is already included in the main project.
            # Without this, you'd see errors when you archive like:
            # "Multiple commands produce ... libReact.a"
            # "Multiple commands produce ... libyoga.a"

            targets_to_ignore = %w(React yoga)

            if targets_to_ignore.include? target.name
              target.remove_from_project
            end
          end
      end
end
